config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'
  get 'welcome/features'
  get 'welcome/contact'
  get 'welcome/sign_up'
  get 'welcome/log_in'
  get 'log_in' => 'sessions#new'
  post 'log_in' => 'sessions#create'
  delete 'log_out' => 'sessions#destroy'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true
  include Gravtastic
  gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Thanks for joining!"
      redirect_to @user
    else
      render 'welcome/sign_up'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:succes] = "User deleted"
    redirect_to users_url
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to log_in_url
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def admin_user
    redirect_to(root_url) unless current_user.executive?
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def features
  end
  def contact
  end
  def sign_up
    @user = User.new
  end
  def log_in
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active(path)
    "active" if current_page?(path)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SideProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "welcome" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'SideProject', welcome_index_path, :class=> 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
      <% if logged_in? %>
        
      <% else %>
        <li class="<%= active(welcome_index_path) %>"><%= link_to 'Home', welcome_index_path %></li>
        <li class="<%= active(welcome_features_path) %>"><%= link_to 'Features', welcome_features_path %></li>
        <li class="<%= active(welcome_contact_path) %>"><%= link_to 'Contact', welcome_contact_path %></li>
      <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <% if current_user.executive? %>
            <li class="divider"></li>
            <li><%= link_to "Manage Users", users_path %></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to "Log out", log_out_path, method: "delete" %></li>
      <% else %>
        <li class="<%= active(log_in_path) %>"><%= link_to 'Log in', log_in_path %></li>
        <li class="<%= active(welcome_sign_up_path) %>"><%= link_to 'Sign up', welcome_sign_up_path %></li>
      <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<%= yield %>

<%= debug(params) if Rails.env.development? && !current_page?(welcome_index_path) %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="navbar-padding"></div>
<div class="navbar-padding"></div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Update your profile</h1>
    <div class="gravatar_edit form-group">
      <%= image_tag @user.gravatar_url %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="navbar-padding"></div>
<div class="navbar-padding"></div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">All Users</h1>
    <ul class="list-group">
      <% @users.each do |user| %>
        <li class="list-group-item">
          <%= image_tag user.gravatar_url %>
          <%= link_to user.email, user %>
          <% if current_user.executive? && !current_user?(user) %>
            <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, user, method: :delete, data: { confirm: "You sure?" }, class: 'pull-right' %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="navbar-padding"></div>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<%= image_tag @user.gravatar_url %>
<p class="lead"><%= @user.email %></p>

app/views/welcome/contact.html.erb
<div class="navbar-padding"></div>
<div class="navbar-padding"></div>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well well-sm">
        <form class="form-horizontal" method="post">
          <fieldset>
            <legend class="text-center header">Contact us</legend>

            <div class="form-group">
              <div class="col-md-10 col-md-offset-1">
                <input id="fname" name="name" type="text" placeholder="First Name" class="form-control">
              </div>
            </div>
            
            <div class="form-group">
              <div class="col-md-10 col-md-offset-1">
                <input id="lname" name="name" type="text" placeholder="Last Name" class="form-control">
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-10 col-md-offset-1">
                <input id="email" name="email" type="text" placeholder="Email Address" class="form-control">
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-10 col-md-offset-1">
                <input id="phone" name="phone" type="text" placeholder="Phone" class="form-control">
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-10 col-md-offset-1">
                <textarea class="form-control" id="message" name="message" placeholder="Enter your massage for us here. We will get back to you as quickly as possible." rows="7"></textarea>
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary btn-lg">Submit</button>
              </div>
            </div>
          </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/welcome/features.html.erb
<div class="navbar-padding"></div>
<div class="navbar-padding"></div>
<div class="navbar-padding"></div>

<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- Three columns of text below the carousel -->
  <div class="row">
    <div class="col-lg-4">
      <img class="img-circle" src="/images/140x140.gif" alt="Generic placeholder image" width="140" height="140">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="img-circle" src="/images/140x140.gif" alt="Generic placeholder image" width="140" height="140">
      <h2>Heading</h2>
      <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
    <div class="col-lg-4">
      <img class="img-circle" src="/images/140x140.gif" alt="Generic placeholder image" width="140" height="140">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div><!-- /.col-lg-4 -->
  </div><!-- /.row -->


  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
      <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-responsive center-block" src="/images/500x500.gif" alt="Generic placeholder image">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 col-md-push-5">
      <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
      <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>
    <div class="col-md-5 col-md-pull-7">
      <img class="featurette-image img-responsive center-block" src="/images/500x500.gif" alt="Generic placeholder image">
    </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
      <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-responsive center-block" src="/images/500x500.gif" alt="Generic placeholder image">
    </div>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->


  <!-- FOOTER -->
  <footer>
    <p class="pull-right"><a href="#">Back to top</a></p>
    <p>&copy; 2016 SideProject &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>

</div> <!-- /container -->

app/views/welcome/index.html.erb
<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      
      <div class="inner cover">
        <h1 class="cover-heading">Set objective goals.</h1>
        <p class="lead">Then stick to them.</p>
        <!--<p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>-->
        <p class="lead">
          <%= link_to 'Learn how', welcome_features_path, :class => 'btn btn-lg btn-default' %>
        </p>
      </div>
      
      <div class="mastfoot">
        <div class="inner">
          <p>Brought to you by SideProject.</p>
        </div>
      </div>
      
    </div>
  </div>
</div>

app/views/welcome/sign_up.html.erb
<div class="navbar-padding"></div>
<div class="navbar-padding"></div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Sign up</h1>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>